version: '3'
services:
  database:
    image: mysql:8.0.31
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: monitoring
      TZ: ${TZ}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database-data:/var/lib/mysql
  redis:
    image: redis:7.0.10
    container_name: redis
  argus:
    image: ben3329/argus:latest
    container_name: argus
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DB_HOST: database
      DB_PASSWORD: ${PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      TZ: ${TZ}
      REDIS_HOST: redis
    ports:
      - 80:8080
    volumes:
      - ./logs:/var/log/argus
      - ./config:/etc/argus
    depends_on:
      - database
      - redis
  celery-worker:
    image: ben3329/argus-celery-worker:latest
    container_name: celery-worker
    environment:
      REDIS_HOST: redis
      DB_PASSWORD: ${PASSWORD}
    volumes:
      - ./logs:/var/log/argus
      - ./config:/etc/argus
    depends_on:
      - redis
  scrape:
    image: ben3329/scrape:latest
    container_name: scrape
    environment:
      REDIS_HOST: redis
      DB_HOST: database
      DB_PASSWORD: ${PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./logs:/var/log/scrape
    depends_on:
      - redis
      - argus