FROM python:3.11.1
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install -y wait-for-it ssh
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
COPY scrape/ /app
WORKDIR /app
RUN pip install -r /app/requirements.txt
CMD [ "./run.sh" ]